### ISSUE TITLE
Non reactive simple example

### ISSUE THREAD

**Issue by deneuxj** [dotnet-websharper/suave#1]
Using the code bellow, connecting to localhost:9000 with my web browser shows no progress. When I kill the server process, the client receives am ERR_CONNECTION_REFUSED.

Using the log in verbose mode, there appear to be two issues. The first is that suave attempted to return an BAD_REQUEST code, which I think indicates something went wrong in websharper.suave, but I don't know what. The second problem is that this BAD_REQUEST code never makes it to the client, due to a socket error, possibly a suave issue.

``` fsharp
open Suave.Web
open WebSharper.Suave
open Suave.Types
open System.Net
open System
open Suave.Logging
open WebSharper
open WebSharper.Sitelets

let MySite =
    Application.SinglePage(fun ctx -> Content.Text("Hello world"))

[<EntryPoint>]
let main argv = 
    let config =
        { defaultConfig with
            bindings = [ { scheme = Protocol.HTTP ; socketBinding = { ip = IPAddress.Loopback ; port = 9000us } } ]
            logger = Loggers.saneDefaultsFor LogLevel.Verbose
        }
    startWebServer config (WebSharperAdapter.ToWebPart MySite)
    0
```

The log contained these lines:

```
[V] 2015-10-19T16:34:38.4130658Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2015-10-19T16:34:38.4310882Z: listener started in 15.019 ms with binding 127.0.0.1:9000 [Suave.Tcp.tcpIpServer]
[V] 2015-10-19T16:34:43.1699710Z: 127.0.0.1 connected, total: 2 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-19T16:34:43.1699710Z: 127.0.0.1 connected, total: 2 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-19T16:34:43.1729605Z: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:43.1729605Z: reserving buffer: 802816, free count: 98 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:43.1779760Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-10-19T16:34:43.1779760Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-10-19T16:34:43.1789681Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-10-19T16:34:43.1789681Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-10-19T16:34:43.1899963Z: reserving buffer: 794624, free count: 97 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:43.1899963Z: reserving buffer: 786432, free count: 96 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:43.2009955Z: reading headers [Suave.Web.processRequest]
[V] 2015-10-19T16:34:43.2050005Z: freeing buffer: 794624, free count: 97 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:43.2120152Z: parsing post data [Suave.Web.processRequest]
[V] 2015-10-19T16:34:43.2150129Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-10-19T16:34:43.2971250Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-10-19T16:34:53.1631597Z: freeing buffer: 786432, free count: 98 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:53.1641609Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-10-19T16:34:53.1661635Z: Socket error while sending BAD_REQUEST, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2015-10-19T16:34:53.1661635Z: freeing buffer: 811008, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-19T16:34:53.1671647Z: 127.0.0.1 disconnected, total: 1 clients [Suave.Tcp.tcpIpServer.job]
```

**Comment by deneuxj** [comment]
I forgot to mention the version of websharper.suave: 3.5.3.16 (retrieved with nuget) and suave: 0.32.1

**Comment by granicz** [comment]
Does it work with Suave 0.32.0-owin2?

**Comment by deneuxj** [comment]
I don't know, I can't compile it. Not sure how the build system works. I checked out suave 0.32.0-owin2, built it, dropped the assembly in websharper.suave/packages/Suave.../lib, ran build.cmd and got a compilation error

``` verbatim
WebSharper.Suave\Main.fs(43,16): error FS0001: Type mismatch. Expecting a
    MidFunc -> WebPart
but given a
    WebPart
The type 'MidFunc' does not match the type 'HttpContext'
```

**Comment by kevinmoesker** [comment]
The same problem appears when trying to get to the "/about" page using the client/server suave VS template. (Suave.0.32.1) The the browser keeps waiting and the verbose log shows the "Socket error while sending BAD_REQUEST". I also get the "ERR_CONNECTION_REFUSED" when server is killed.

I was trying to see how the suave request routing and websharper request routing "play together". Unfortunately it doesn't work

```
[V] 2015-10-20T13:39:59.4693180Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2015-10-20T13:39:59.7384970Z: listener started in 294.200 ms with binding 127.0.0.1:9000 [Suave.Tcp.tcpIpServer]
[V] 2015-10-20T13:40:15.4191650Z: 127.0.0.1 connected, total: 3 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-20T13:40:15.4191650Z: 127.0.0.1 connected, total: 3 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-20T13:40:15.4201601Z: 127.0.0.1 connected, total: 3 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-20T13:40:15.4391783Z: reserving buffer: 802816, free count: 98 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.4401760Z: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.4411784Z: reserving buffer: 794624, free count: 97 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.4601919Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:15.4601919Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:15.4611900Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:15.4641924Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-10-20T13:40:15.4651931Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-10-20T13:40:15.4641924Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-10-20T13:40:15.5232342Z: reserving buffer: 786432, free count: 96 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.5242298Z: reserving buffer: 778240, free count: 95 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.5242298Z: reserving buffer: 770048, free count: 94 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.5962777Z: reading headers [Suave.Web.processRequest]
[V] 2015-10-20T13:40:15.6131145Z: freeing buffer: 770048, free count: 95 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:15.6601453Z: parsing post data [Suave.Web.processRequest]
[V] 2015-10-20T13:40:15.6741547Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:16.0584072Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-10-20T13:40:25.3847490Z: freeing buffer: 786432, free count: 96 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:25.3857509Z: freeing buffer: 778240, free count: 97 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:25.3907589Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:25.3887525Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:25.5828867Z: Socket error while sending BAD_REQUEST, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:25.5828867Z: Socket error while sending BAD_REQUEST, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2015-10-20T13:40:25.5868889Z: freeing buffer: 802816, free count: 98 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:25.5878853Z: freeing buffer: 794624, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-10-20T13:40:25.5938936Z: 127.0.0.1 disconnected, total: 1 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-10-20T13:40:25.5918987Z: 127.0.0.1 disconnected, total: 2 clients [Suave.Tcp.tcpIpServer.job]
```

**Comment by Tarmil** [comment]
The issue is caused by the fact that `Application.SinglePage` doesn't ignore final slashes in URLs, and the URL received from Suave is "http://localhost:9000//" (note the double slash). I am fixing this in WebSharper itself.

@kevinmoesker however I can't seem to reproduce your version of the issue. Are you using the template code "as is"? If not, can you post here your code?

**Comment by kevinmoesker** [comment]
What I do to reproduce the issue:
- create a new project using the ""UI.Next Client-Server Application with Suave" template "as is", 
- start it (debug mode) and try to get the /about page
  my issue: the about page does not show and i see the browser waiting

How I reproduce the "Socket error while sending BAD_REQUEST" in the suave log
- modify the "Main.fs" code a little bit to start suave in verbose log mode like @deneuxj
- start the project and again try to get the /about page from a browser 
- close the browser window.

The Socket error while sending BAD_REQUEST message will not show before you close the browser window.

So @Tarmil for you the "/about" page is working? Websharper multipage routing combines well with suave? Do you have any suggestions on what I could try, or what info would help you, to make this work?

```
namespace Application1

open WebSharper
open WebSharper.Sitelets
open WebSharper.UI.Next
open WebSharper.UI.Next.Server

type EndPoint =
    | [<EndPoint "/">] Home
    | [<EndPoint "/about">] About

module Templating =
    open WebSharper.UI.Next.Html

    type MainTemplate = Templating.Template<"Main.html">

    // Compute a menubar where the menu item for the given endpoint is active
    let MenuBar (ctx: Context<EndPoint>) endpoint : Doc list =
        let ( => ) txt act =
             liAttr [if endpoint = act then yield attr.``class`` "active"] [
                aAttr [attr.href (ctx.Link act)] [text txt]
             ]
        [
            li ["Home" => EndPoint.Home]
            li ["About" => EndPoint.About]
        ]

    let Main ctx action title body =
        Content.Page(
            MainTemplate.Doc(
                title = title,
                menubar = MenuBar ctx action,
                body = body
            )
        )

module Site =
    open WebSharper.UI.Next.Html

    let HomePage ctx =
        Templating.Main ctx EndPoint.Home "Home" [
            h1 [text "Say Hi to the server!"]
            div [client <@ Client.Main() @>]
        ]

    let AboutPage ctx =
        Templating.Main ctx EndPoint.About "About" [
            h1 [text "About"]
            p [text "This is a template WebSharper client-server application."]
        ]

    let Main =
        Application.MultiPage (fun ctx endpoint ->
            match endpoint with
            | EndPoint.Home -> HomePage ctx
            | EndPoint.About -> AboutPage ctx
        )

    open WebSharper.Suave
    open Suave.Web
    open Suave.Types
    open System.Net
    open Suave.Logging


    let config =
        { defaultConfig with
            bindings = [ { scheme = Protocol.HTTP ; socketBinding = { ip = IPAddress.Loopback ; port = 9000us } } ]
            logger = Loggers.saneDefaultsFor LogLevel.Verbose
        }

    do startWebServer config (WebSharperAdapter.ToWebPart Main)
```

**Comment by Tarmil** [comment]
Okay, I can now actually reproduce too. It is also a double slash issue, I am looking into it. It might be a problem with how we handle `owin.RequestPathBase`.
